// The agent-workhorse spine: parse onyx-bridge project logs and build the
// one-file digest agents read to orient. Pure; never throws on weird input.
import { dayKey } from './stats.mjs'
import { topTags } from './dashboard.mjs'

export const PROJECT_FOLDER = 'Claude Projects'
export const DIGEST_ID = PROJECT_FOLDER + '/_AGENT.md'
export const DIGEST_MARKER = '<!-- onyx:agent-digest'

const FM_RE = /^---\r?\n[\s\S]*?\r?\n---\r?\n?/
const DATED = /^(\d{4}-\d{2}-\d{2})\s*(?:[—–-]\s*)?(.*)$/

// → { status, done:[{date,text}], next:[string], decisions:[{date,text}] }
export function parseProjectLog(content) {
  const out = { status: '', done: [], next: [], decisions: [] }
  const body = String(content || '').replace(FM_RE, '')
  let cur = null
  let statusLines = []
  const pushBullet = (list, text) => {
    if (list === out.next) {
      list.push(text)
      return
    }
    const m = text.match(DATED)
    if (m) list.push({ date: m[1], text: m[2] })
    else list.push({ date: null, text })
  }
  for (const line of body.split(/\r?\n/)) {
    const h = line.match(/^##\s+(.+?)\s*$/)
    if (h) {
      const k = h[1].toLowerCase()
      cur = k.startsWith('status') ? 'status' : k.startsWith('done') ? 'done' : k.startsWith('next') ? 'next' : k.startsWith('decision') ? 'decisions' : null
      continue
    }
    if (!cur || /^#/.test(line)) continue
    if (cur === 'status') {
      if (line.trim()) statusLines.push(line.trim())
      continue
    }
    const b = line.match(/^\s*[-*+]\s+(.*)$/)
    const list = out[cur]
    if (b) pushBullet(list, b[1].trim())
    else if (line.trim() && list.length) {
      // continuation of a wrapped bullet
      const last = list[list.length - 1]
      if (typeof last === 'string') list[list.length - 1] = last + ' ' + line.trim()
      else last.text += ' ' + line.trim()
    }
  }
  out.status = statusLines.join(' ').replace(/\s+/g, ' ')
  return out
}

export function lastDoneDate(log) {
  let max = null
  for (const d of log?.done || []) {
    if (d.date && (!max || d.date > max)) max = d.date
  }
  return max
}

export function isStale(log, mtime, now, days = 7) {
  const last = lastDoneDate(log)
  const cutoff = dayKey(now - days * 86400000)
  if (last) return last < cutoff
  return mtime ? dayKey(mtime) < cutoff : true
}

export function collectProjects(notes) {
  return notes
    .filter((n) => n.projectLog && !n.path.split('/').pop().startsWith('_'))
    .sort((a, b) => (b.mtime || 0) - (a.mtime || 0))
}

// Onyx only ever clobbers digests it authored (or creates fresh)
export function canOverwriteDigest(raw) {
  return raw == null || String(raw).includes(DIGEST_MARKER)
}

// deterministic given (graph, now, version) — snapshot-testable
export function buildAgentDigest({ graph, now, version = '0.0.0' }) {
  const d = new Date(now)
  const pad = (n) => String(n).padStart(2, '0')
  const stamp = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`
  const words = graph.notes.reduce((s, n) => s + (n.wordCount || 0), 0)
  const orphans = graph.notes.filter((n) => !n.inLinks?.length && !n.outLinks?.length).length
  const tags = topTags(graph.notes).slice(0, 10).map((t) => `#${t.tag} ×${t.count}`).join(', ')
  const projects = collectProjects(graph.notes)

  const lines = []
  lines.push('---', 'title: _AGENT', 'type: agent-digest', '---', '')
  lines.push(`${DIGEST_MARKER} · generated by Onyx v${version} · ${new Date(now).toISOString()} · do not hand-edit -->`)
  lines.push(`# Agent Digest · ${stamp}`, '')
  lines.push('## Vault')
  lines.push(`- ${graph.meta.noteCount} notes · ${graph.meta.linkCount} links · ${words.toLocaleString()} words · ${orphans} orphans`)
  lines.push(`- top tags: ${tags || 'none'}`, '')
  lines.push(`## Active Projects (${projects.length})`)
  for (const p of projects) {
    const log = p.projectLog
    const last = lastDoneDate(log)
    lines.push(`### ${p.title} — last touch ${dayKey(p.mtime || now)}`)
    if (log.status) lines.push(`Status: ${log.status.slice(0, 400)}`)
    if (log.next.length) {
      lines.push('Next:')
      for (const n of log.next) lines.push(`- ${n}`)
    }
    if (last) {
      const entry = log.done.filter((x) => x.date === last).pop()
      lines.push(`Last done: ${last} — ${entry?.text || ''}`)
    }
    lines.push(`Decisions: ${log.decisions.length} — read [[${p.path.split('/').pop().replace(/\.md$/, '')}]] before working`, '')
  }
  lines.push('## Contract')
  lines.push(`- Full logs: ${PROJECT_FOLDER}/<name>.md · read ## Done before redoing anything`)
  return lines.join('\n') + '\n'
}
